<?php
/**
 * Front page template
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( wp_is_mobile() ) {
	locate_template( 'page-templates/template-home-mobile.php', true, false );
	return;
}

$issue_items = require get_template_directory() . '/inc/home-issue-items.php';

if ( ! is_array( $issue_items ) ) {
	$issue_items = array();
}

$issue_css = get_stylesheet_directory() . '/assets/css/home-issue-carousel.css';
$issue_js  = get_stylesheet_directory() . '/assets/js/home-issue-carousel.js';

wp_enqueue_style(
	'glandore-home-issue-carousel',
	get_stylesheet_directory_uri() . '/assets/css/home-issue-carousel.css',
	array(),
	file_exists( $issue_css ) ? filemtime( $issue_css ) : null
);

wp_enqueue_script(
	'glandore-home-issue-carousel',
	get_stylesheet_directory_uri() . '/assets/js/home-issue-carousel.js',
	array(),
	file_exists( $issue_js ) ? filemtime( $issue_js ) : null,
	true
);

get_header();
?>

<div class="home-page">
	<div class="home-desktop-landing">
		<div class="landing-background" data-home-url="<?php echo esc_url( home_url( '/' ) ); ?>">
			<div class="landing-overlay"></div>

			<main class="landing-content">
				<div class="landing-content-row">
					<div class="landing-intro-content">
						<div class="landing-copy landing-copy--desktop">
							<?php get_template_part( 'template_parts/intro', 'desktop' ); ?>
						</div>

						<div class="landing-copy landing-copy--laptop">
							<?php get_template_part( 'template_parts/intro', 'laptop' ); ?>
						</div>
					</div>

					<?php if ( ! empty( $issue_items ) ) : ?>
						<aside class="landing-featured-panel landing-issue-panel" aria-label="Explore The Issue Studio">
							<div class="issue-carousel js-issue-carousel">
								<h2 class="issue-carousel__kicker">
									<?php esc_html_e( 'Explore The Issue Studio', 'glandore' ); ?>
								</h2>

								<div class="issue-carousel__track">
									<?php foreach ( $issue_items as $index => $item ) : ?>
										<?php
										$title   = isset( $item['title'] ) ? $item['title'] : '';
										$url     = isset( $item['url'] ) ? $item['url'] : '';
										$excerpt = isset( $item['excerpt'] ) ? $item['excerpt'] : '';
										?>
										<article class="issue-carousel__slide<?php echo 0 === $index ? ' is-active' : ''; ?>" aria-hidden="<?php echo 0 === $index ? 'false' : 'true'; ?>">
											<p class="issue-carousel__label">
												<?php esc_html_e( 'Issue', 'glandore' ); ?>
											</p>

											<h3 class="issue-carousel__issue">
												<a href="<?php echo esc_url( $url ); ?>">
													<?php echo esc_html( $title ); ?>
												</a>
											</h3>

											<?php if ( ! empty( $excerpt ) ) : ?>
												<div class="issue-carousel__assessment">
													<p class="issue-carousel__assessment-label">
														<?php esc_html_e( 'Overall Assessment (generated by Tychevia)', 'glandore' ); ?>
													</p>

													<div class="issue-carousel__excerpt is-collapsed">
														<?php echo nl2br( esc_html( $excerpt ) ); ?>

														<p class="issue-carousel__cta">
															<a href="<?php echo esc_url( $url ); ?>">
																<?php esc_html_e( 'Open in Issue Studio', 'glandore' ); ?>
															</a>
														</p>
													</div>

													<button type="button" class="issue-carousel__more" aria-expanded="false">
														<?php esc_html_e( 'More', 'glandore' ); ?>
													</button>
												</div>
											<?php endif; ?>
										</article>
									<?php endforeach; ?>
								</div>

								<?php if ( count( $issue_items ) > 1 ) : ?>
									<div class="issue-carousel__controls">
										<button type="button" class="issue-carousel__nav issue-carousel__nav--prev">
											<?php esc_html_e( 'Previous', 'glandore' ); ?>
										</button>

										<div class="issue-carousel__dots" aria-hidden="true">
											<?php foreach ( $issue_items as $index => $item ) : ?>
												<span class="issue-carousel__dot<?php echo 0 === $index ? ' is-active' : ''; ?>"></span>
											<?php endforeach; ?>
										</div>

										<button type="button" class="issue-carousel__nav issue-carousel__nav--next">
											<?php esc_html_e( 'Next', 'glandore' ); ?>
										</button>
									</div>
								<?php endif; ?>
							</div>
						</aside>
					<?php endif; ?>
				</div>
			</main>
		</div>
	</div>
</div>

<div class="login-modal-overlay" id="login-modal-overlay" hidden></div>

<div class="login-modal-panel" id="login-modal-panel" hidden role="dialog" aria-modal="true" aria-labelledby="login-modal-title">
	<div class="login-modal-inner">
		<button type="button" class="login-modal-close" id="login-modal-close" aria-label="Close login panel">×</button>
		<h2 id="login-modal-title" class="login-modal-heading">Member login</h2>
		<div class="login-modal-form">
			<?php echo do_shortcode( '[user_registration_login]' ); ?>
		</div>
	</div>
</div>

<?php get_template_part( 'template_parts/modals/modal-registration' ); ?>

<?php get_footer(); ?>